
dubbo :
  #通信规则（通信协议和接口）
  protocol :
    #暴露服务端口 （默认是20880，修改端口，不同的服务提供者端口不能重复）
    prot : 20881
    name : dubbo
  application :
    name : zc-service-provider
  #注册中心的协议和地址
  registry :
    address : zookeeper://127.0.0.1:2181
  #连接监控中心
  monitor :
    protocol : registry

#开启包扫描，可替代 @EnableDubbo 注解
##dubbo.scan.base-packages=com.zc.gmall





#  spring.datasource.url=
#  spring.datasource.username=root
#  spring.datasource.password=root
#  spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#  #mybatis-plus
#  mybatis-plus.mapper-locations=classpath:com/mht/springbootmybatisplus/mapper/xml/*.xml
#  mybatis-plus.type-aliases-package=com.mht.springbootmybatisplus.entity

#mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#mybatis-plus
mybatis-plus:
  ## 配置扫描xml
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.zc.bean
